import os
import webbrowser
import pandas as pd
from pyvis.network import Network

net = Network(
    height="100vh", 
    width="100%", 
    bgcolor="#222222", 
    font_color="white", 
    cdn_resources='remote'
)

csv_file = "Animal_links.csv" # TEST NAME make sure to change this to the name of your csv file generated by the crawler or it won't work
if not os.path.exists(csv_file):
    print(f"Error: {csv_file} not found. Run your crawler first!")
else:
    df = pd.read_csv(csv_file)

    all_nodes = pd.concat([df['Source'], df['Target']])
    degree_counts = all_nodes.value_counts().to_dict() 

    for index, row in df.iterrows():
        source = str(row['Source'])
        target = str(row['Target'])

        source_degree = degree_counts.get(source, 1)
        target_degree = degree_counts.get(target, 1)

        net.add_node(source, label=source, size=10 + (source_degree * 2)) # label=source and label=target are important or it throws an error
        net.add_node(target, label=target, size=10 + (target_degree * 2))
        
        net.add_edge(source, target)

    net.force_atlas_2based()

    output_filename = "wikipedia_map.html"
    path = os.path.abspath(output_filename)
    
    net.write_html(path)
    print(f"Success! Map generated with {len(df)} connections.")
    webbrowser.open('file://' + path)